### ISSUE TITLE
Missing step in Microsoft auth documentation

### ISSUE THREAD

**Issue by Odonno** [pwa-builder/pwa-auth#10]
I tried to integrate MS auth in my app with the simple pwa-auth web component. I followed all the steps in the documentation but auth did not work...

Hopefully, I found a solution provided by @nmetulev here https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/91#issuecomment-494494475

Checking `access tokens` and `ID tokens` perfectly solved the problem. I believe we should add this as a new step in the doc.

**Comment by davrous** [comment]
Thanks @Odonno for the report! @JudahGabriel, can you please update your doc to add this additional step in case of a SPA?

**Comment by JudahGabriel** [comment]
I'll add this today. Thanks for the heads up, @Odonno.

**Comment by JudahGabriel** [comment]
@Odonno I've [updated the docs](https://github.com/pwa-builder/pwa-auth/blob/master/creating-microsoft-key.md#step-5-enable-access-tokens) to include the `access token` and `ID token` step. Thanks!

**Comment by Odonno** [comment]
Good. Thank you.
