### ISSUE TITLE
How to use it inside a react app?

### ISSUE THREAD

**Issue by afcastano** [pwa-builder/pwa-auth#12]
Hello, can you provide any examples of using the web component inside a react app?
I have imported the module successfully:
`yarn add @pwabuilder/pwaauth`

Then in my *.tsx file, I am doing this:

```tsx
import '@pwabuilder/pwaauth';
...
...
render () {
   return <div><pwa-auth /></div>;
}
```

and I am getting this error:

```
Property 'pwa-auth' does not exist on type 'JSX.IntrinsicElements'.
```

I feel that I am missing something very simple here, but I can't figure out what is it... Any ideas?
Thanks!

**Comment by JudahGabriel** [comment]
[Here's a sample](https://github.com/nmetulev/wc-react/issues/1) that uses wc-react. In a nutshell:

Install packages:
```
yarn add @pwabuilder/pwaauth wc-react
```

Use it:
```jsx
import React from 'react';
import { wrapWc } from 'wc-react';
import '@pwabuilder/pwaauth';

const PwaAuth = wrapWc('pwa-auth');

const Login = (props: any) => {
    return (
        <div>
            <PwaAuth 
                microsoftKey="123456abc"
                googleKey="123456abc"
                facebookKey="123456abc"
                appearance="list"
            />
        </div>
    );
};
```

**Comment by afcastano** [comment]
Thanks Judah,
This might be silly, but I am trying your solution and despite it compiles in typescrypt, I haven't been able to get the 'pwa-auth' reference to add the `addEventListener('signin-completed'` event.

I am getting `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

I am using forwardRef around the wc-react component like so:
tsx```
const PwaAuth = wrapWc('pwa-auth');
      const WithRef = React.forwardRef((props, ref) => (
        <PwaAuth
          googleKey="xxx"
          appearance="list"
          ref={ref}
        />
      ));
      loginButton = <WithRef ref={this.pwaAuthRef}/>;
```

But I am still getting the issue.
Any ideas?

**Comment by JudahGabriel** [comment]
I'm not sure what the issue is. I will look at this in a few days - currently heads down for BUILD. In the meantime, if you solve this, let us know.

**Comment by JudahGabriel** [comment]
OK, even without wc-react, try something like this:

```jsx
import React from 'react';
import '@pwabuilder/pwaauth';

const App: React.FunctionComponent = () => {
  return <pwa-auth
          appearance="list"
          ref={(element) => {
            if (!element) {
              return;
            }

            // the event listener needs to be removed
            // when the element is unloaded - not shown here
            element.addEventListener('signin-completed', (e) => log.debug('Sign in completed!'));
          }}>
          </pwa-auth>;
};
```

**Comment by afcastano** [comment]
Hello Judah, sorry for the late reply.
Maybe my problem was related to Typescript and not to the component itself.

So, I got it working defining the `pwa-auth` entry in the `IntrinsicElements` interface on the `global.JSX` namespace like so:

```tsx
declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      'pwa-auth': MyPWAAuth
    }
  }
}
```

Now I can use the component directly on my `tsx` code:
```tsx
import '@pwabuilder/pwaauth';
...
...
<pwa-auth 
   googleKey="xxx"
   appearance="list"
   ref={this.pwaAuthRef}/>
```

Then, the event can be handled like so:
```tsx
import {SignInResult} from '@pwabuilder/pwaauth/build/signin-result'  
...
...
handleLogin(event: Event) {
    const result = (event as CustomEvent).detail as SignInResult;
    log.debug(`Sign in completed! ${JSON.stringify(result)}`);
}
...
...
componentDidUpdate() {
  this.pwaAuthRef.current.removeEventListener('signin-completed', this.handleLogin.bind(this));
}
```

The unfortunate thing is that the `ts` definitions are not in the root of the project, hence the weird import:
```tsx
import {SignInResult} from '@pwabuilder/pwaauth/build/signin-result'  
```

Also, the `PwaAuth` typescript definition file found in `@pwabuilder/pwaauth/build/pwa-auth.d.ts` 
could be improved by marking all of the fields as optional. As of now, It requires the to define all of them: `microsoftButtonText`, `googleButtonText`, `facebookButtonText` etc...

That is why I have to come with my own definition:
```tsx
type MyPWAAuth = 
  React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>
  & {
    googleKey: string | undefined | null;
    appearance: "button" | "list" | "none";
  }
```

These shouldn't be too difficult to fix. If you don't mind, I'll raise an issue and a PR to define the types in the coming days.

Cheers

**Comment by JudahGabriel** [comment]
Thanks for the feedback. I'd be glad to accept a PR.

**Comment by JudahGabriel** [comment]
Bump @afcastano you still going to issue a PR for this? I'd be glad to accept that.

**Comment by afcastano** [comment]
Hello @JudahGabriel, Sorry for the delay... I've been super busy these days. 
I'll try to do it soon (this week?) 
Cheers,
Andres

**Comment by afcastano** [comment]
Hello @JudahGabriel, I am preparing the PR. I am thinking in two approaches: 

1 - The simplest that I can do is to add `types.ts` to `src` and export all the types in there. Then I can reference them in the `package.json`

2- The other thing I can do is to add an `index.ts` exporting everything and using that one instead of `pwa-auth.ts`. THis will be a more standard approach but I feel that this might require more changes.

I will try and submit 1 and see how it goes.
Cheers

**Comment by afcastano** [comment]
Sorry hit the wrong button...  :)

**Comment by afcastano** [comment]
Hello, I didn't end up creating the `types.ts` file, since the types I had to export were almost all of them in `pwa-auth.ts`.

With this change, the way you can use it in react is:
```jsx
import '@pwabuilder/pwaauth';
import { SignInResult, PwaAuth } from '@pwabuilder/pwaauth';

type ReactPwaAuth = React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & PwaAuth;

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      'pwa-auth': ReactPwaAuth
    }
  }
}

...
// Inside funcitional component or render
return (<pwa-auth 
                      googleKey="xxxx"
                      appearance="list"
                      ref={this.pwaAuthRef}/>);
```

The event can be listen like this:
```jsx
...
import { SignInResult, PwaAuth } from '@pwabuilder/pwaauth';
// Inside a component
pwaAuthRef = React.createRef<HTMLElement & PwaAuth>();
...
registerLoginListener() {
    if(this.pwaAuthRef && this.pwaAuthRef.current) {
      this.pwaAuthRef.current.addEventListener('signin-completed', this.handleLogin.bind(this));
    }
  }

  handleLogin(event: Event) {
    const result:SignInResult = (event as CustomEvent<SignInResult>).detail;
    ...
  }
```

Also you could manually trigger the sign in like so:
```jsx
       this.pwaAuthRef.current.signIn('Google').then(result => {
          log.debug(`Sign in completed! ${result.providerData}`);
        });
```

**Comment by JudahGabriel** [comment]
Thanks for the PR!
