### ISSUE TITLE
No one work for me

### ISSUE THREAD

**Issue by rajandimri** [pwa-builder/pwa-auth#2]
Hello there,

This is something pretty cool feature.  The users can use the PWA Oauth to login to their account using the social plugins. 

But I follow the steps and faced the problems for all the platforms i.e FB, Microsoft, and Google. 
1. Facebook - Followed the steps and when clicking on the login button once, I was able to the login form but it didn't redirect me to my signing account even I received the email from Facebook that I have logged in, but nothing happened. (Login Button doesn't seem to be working in iOS)

2. Microsoft - Please check the error below - 
![image](https://user-images.githubusercontent.com/15828863/79273077-0c18e480-7ec0-11ea-878f-1aca7eb74ec5.png) (Login Button doesn't seem to be working in iOS)

3 Google - Please check the error below -
![image](https://user-images.githubusercontent.com/15828863/79273302-69149a80-7ec0-11ea-8645-b1fbb8d311c0.png) (Login Button doesn't seem to be working in iOS)

Thanks!

**Comment by JudahGabriel** [comment]
It sounds like you forgot to add the proper redirects to your keys.

Here are some examples of what your app key redirects should look like:

Google:
![image](https://user-images.githubusercontent.com/312936/79287311-4363a300-7e78-11ea-9a97-0173d1c476e4.png)

Microsoft:
![image](https://user-images.githubusercontent.com/312936/79287611-33988e80-7e79-11ea-8763-20ad46a1f6fd.png)

Facebook:
![image](https://user-images.githubusercontent.com/312936/79287766-b3265d80-7e79-11ea-96e6-473512b14a02.png)

As for iOS Safari, it looks like Safari is blocking the initial popup. We're [tracking that in here](https://github.com/pwa-builder/pwa-auth/issues/3).

**Comment by rajandimri** [comment]
Hello @JudahGabriel , Thanks for informing me. But I'm not aware of the app key redirects, please can you explain to me what is that, and from where I can get these URLs? 

Thanks!

**Comment by JudahGabriel** [comment]
Sure. We have the explainers for that:

- [Creating a Microsoft key](https://github.com/pwa-builder/pwa-auth/blob/master/creating-microsoft-key.md)
- [Creating a Google key](https://github.com/pwa-builder/pwa-auth/blob/master/creating-google-key.md)
- [Creating a Facebook key](https://github.com/pwa-builder/pwa-auth/blob/master/creating-facebook-key.md)

In particular, look at Step 4. Each key will ask for "redirect_uri". You'll put in the URL to your web app there. That way, your keys can't be reused by other apps. 👍

**Comment by rajandimri** [comment]
I followed the steps as explained. But I didn’t get what is the redurect_uri, I mean from where to get the URL to my web app? Is it the simple URL of my website? 

If yes, then I’ve already entered the URL of my website. And if not, please let me know from where to get these URL??

**Comment by JudahGabriel** [comment]
Looking at the video, it looks like you're successfully signing in. Did you add an event listener for `signin-completed` event?

```javascript
const pwaAuth = document.querySelector("pwa-auth");
pwaAuth.addEventListener("signin-completed", ev => {
    const signIn = ev.detail;
    if (signIn.error) {
        console.error("Sign in failed", signIn.error);
    } else {
        console.log("Email: ", signIn.email);
        console.log("Name: ", signIn.name);
        console.log("Picture: ", signIn.imageUrl);
        console.log("Provider (MS, Google, FB): ", signIn.provider);
        console.log("Raw data from provider: ", signIn.providerData);
    }
});
```

That event should be firing when a user signs in. (Based on your video, this event is firing.)

Once that event fires, do whatever you normally do for signing-in: set a cookie, set a JWT token, etc.

**Comment by rajandimri** [comment]
Still not working, don't know why?

**Comment by JudahGabriel** [comment]
How is sign-in done on your site right now? Are you setting an auth cookie, using a JWT token, or something else?

**Comment by JudahGabriel** [comment]
OK. So your situation is a little different because you're probably not controlling how users are signed-in. My guess is, Shopify is setting an auth cookie once a user signs in. You either need to set that same auth cookie when someone signs-in through pwa-auth, or alternately, detect when pwa-auth signs in, and then "sign them in silently" through Shopify.

I'd suggest searching for how Shopify signs-in users.

**Comment by rajandimri** [comment]
Might be this feature will not work for Shopify, or if you found some documentation on how to integrate with Shopify, Please do let me know!


Thanks!
