### ISSUE TITLE
Please allow styling of the button container.

### ISSUE THREAD

**Issue by shaunakg** [pwa-builder/pwa-auth#20]
It's great that we can customise what the button says but I've not been able to figure out how to change the actual size of the container. Of course, I can make the button break out of the container into whatever width I want but it won't work with `width: 100%`, etc.

Please make the container a `part` in the CSS code.

**Comment by shaunakg** [comment]
It turns out fixing this was easy. I have made a pull request (#21).

**Comment by JudahGabriel** [comment]
Merged. Thanks!
