### ISSUE TITLE
pwa-auth.min.js not works when using from Local Server

### ISSUE THREAD

**Issue by sunBhabani** [pwa-builder/pwa-auth#23]
Dear JudahGabriel,

Really thanks for the module and the feature implemented by you. Great job.

As per your documentation (https://components.pwabuilder.com/component/pwa_auth), i have used src="https://cdn.jsdelivr.net/npm/@pwabuilder/pwaauth@latest/dist/pwa-auth.min.js" & it's works fine for google oAuth in my simple HTML/PHP application.

So i have tried copy all the content of 'pwa-auth.min.js' to an another file which is in my local server, after-that google oAuth does not not works. It's works only from the cloud i.e cdn.jsdeliver.net/npn....

The error say's during my index.php loads (Uncaught SyntaxError: Unexpected token 'export')

Any help of guidance is really appreciated.

**Comment by JudahGabriel** [comment]
The `unexpected token 'export'` error is curious here. When you're impoorting the javascript file, do you have ``type="module"`?

It should look like this:

```js
<script  type="module"  src="pwa-auth.min.js"></script>
```

**Comment by sunBhabani** [comment]
Dear JudahGabriel,,

I have done all the best at my end but still it's not works if the 'js' file calls from local.

Actually your 'pwa-auth.min.js' file does not works from local server instead on CDN. You may pls try at your end and hope you also see the same difficulties.

the console error says:

pwa-auth.min.js:172 GET http://localhost/vendors/google/google-provider-e3c8088c.js net::ERR_ABORTED 404 (Not Found)
importGoogleProvider @ pwa-auth.min.js:172
import @ pwa-auth.min.js:172
(anonymous) @ pwa-auth.min.js:172
loadAllDependencies @ pwa-auth.min.js:172
firstUpdated @ pwa-auth.min.js:172
performUpdate @ pwa-auth.min.js:134
_enqueueUpdate @ pwa-auth.min.js:134
async function (async)
_enqueueUpdate @ pwa-auth.min.js:134
_requestUpdate @ pwa-auth.min.js:134
initialize @ pwa-auth.min.js:134
initialize @ pwa-auth.min.js:172
D @ pwa-auth.min.js:134
Z @ pwa-auth.min.js:172
ee @ pwa-auth.min.js:172
(anonymous) @ pwa-auth.min.js:172
(anonymous) @ pwa-auth.min.js:172
te @ pwa-auth.min.js:172
(anonymous) @ pwa-auth.min.js:172

pwa-auth.min.js:172 Error loading dependencies TypeError: Failed to fetch dynamically imported module: http://localhost/vendors/google/google-provider-e3c8088c.js

**Comment by JudahGabriel** [comment]
Yeah, you're missing files. If you want to run this locally, you'll need to copy [all the files from the CDN](https://www.jsdelivr.com/package/npm/@pwabuilder/pwaauth?path=dist).
