### ISSUE TITLE
manifest.json not updating after a long wait

### ISSUE THREAD

**Issue by sunBhabani** [pwa-builder/pwa-auth#24]
Dear **JudahGabriel,**

Am facing some difficulties on my PWA application that when i modified some parameters in my 'manifest.json' and those changes are not reflect on my users handset. I have wait 2/3 day's more. Sometime also a (week +) but still unsuccessful. Also i have checked all of my Users handset are so latest and all have using Google Chrome > 80 version. I have tried lot of way's refer Google & MDN knowledge base but can't figure out why the 'manifest.json' parameters are not able to update on my users handset automatically.

If a user uninstall the PWA app and again reinstall then all things looks good as per the 'manifest.json'. Basically i have changed (short_name, background_color, theme_color). Any help is deeply appreciated and salute.

Any help is deeply appreciated.

Here is my code snippet:

`{
    "short_name": "LiveX 2020",
    "name": "JSPL SCADA-Live X",
    "lang": "en",
    "description": "Product of TeamSCADA || JSPL Angul",
    "start_url": "/?source=pwa",
    "scope": "/",
    "background_color": "#fbfbfb",
    "theme_color": "#fbfbfb",
    "dir": "ltr",
    "display": "standalone",
    "orientation": "portrait",
    "prefer_related_applications": false,
    "icons": [
        {
            "src": "images/icons/android-icon-36x36.png",
            "sizes": "36x36",
            "type": "image/png"
        },
        {
            "src": "images/icons/android-icon-48x48.png",
            "sizes": "48x48",
            "type": "image/png"
        },
        {
            "src": "images/icons/android-icon-72x72.png",
            "sizes": "72x72",
            "type": "image/png"
        },
        {
            "src": "images/icons/android-icon-96x96.png",
            "sizes": "96x96",
            "type": "image/png"
        },
        {
            "src": "images/icons/android-icon-144x144.png",
            "sizes": "144x144",
            "type": "image/png"
        },
        {
            "src": "images/icons/android-icon-192x192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "images/icons/android-icon-512x512.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ]
}

In my index.php <link rel="manifest" href="/manifest.json">
`

**Comment by JudahGabriel** [comment]
You're in the wrong repo - this is the repo for pwa-auth component. Can you open an issue over at the [main repo](https://github.com/pwa-builder/pwabuilder/issues)?
