### ISSUE TITLE
Having trouble getting this hosted

### ISSUE THREAD

**Issue by jmarshallrevo** [pwa-builder/pwa-auth#35]
This runs fine for me locally in dev
I ran npm run build locally and it looks like it creates a dist folder.

Any idea of what the following inputs should be for the pwa-auth project?  I’ve tried everything on Azure and Vercel (I can get a generic react, or the sample GitHub project you have in the PWA Builder notes deployed without an issue)

So I’m looking for:
app_location: “" # App source code path
api_location: "" # Api source code path - optional
output_location: "" # Built app content directory - optional

Thanks

**Comment by jmarshallrevo** [comment]
Never mind!  Found the issue

**Comment by VityaSchel** [comment]
> Never mind! Found the issue

Nice! Would you mind posting it here for future visitors?
