### ISSUE TITLE
Safari & Firefox support

### ISSUE THREAD

**Issue by balupton** [pwa-builder/pwa-auth#5]
Reading up on the apis - https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer - that the medium article linked, it seems this is a chromium only thing. However the signin process does seem to work on iOS safari. Is there a fallback happening? What are the considerations that users of this library need to be aware of for a safari and firefox audience?

**Comment by balupton** [comment]
Thinking about this further after watching
https://youtu.be/NJ-sphu2DqQ

What if the "fallback" for Safari was presenting Signin with Apple? I'm sure most die-hard safari users would go for that instead of those provided. I know I would.

**Comment by JudahGabriel** [comment]
Hi, thanks for the question and feedback. 😎

**Fallback**: Yep! pwa-auth is a progressive enhancement, meaning we light up on browsers that support the new APIs, but fallback standard OAuth where unavailable. From [the docs](https://www.pwabuilder.com/feature/Sign%20In%20with%20Microsoft,%20Google,%20Facebook), 

> "With regards to browser support, pwa-auth credential management is a progressive enhancement: on browsers that don't support Credential Management, pwa-auth will fallback to credentialmode="none" behavior, which means the usual OAuth flow is invoked every time."

This means pwa-auth will still work on Safari and Firefox. It can work on IE as well if you add the Web Components polyfill.

**Sign in With Apple**: I'll make this happen; you're the second person to ask. I'll update this post when it's implemented.

**Comment by JudahGabriel** [comment]
For Sign in with Apple, I'm tracking that in #6. Closing this issue.

**Comment by JudahGabriel** [comment]
Update: we've [implemented Sign in with Apple](https://github.com/pwa-builder/pwa-auth/issues/6#issuecomment-618223788).
