### ISSUE TITLE
Recommendations for more signin providers?

### ISSUE THREAD

**Issue by balupton** [pwa-builder/pwa-auth#6]
I'm keen to see Signin with Apple, as well as a Goodreads option, and a Discourse option - not sure if either can be done using the credentials api this uses, or if they should be done as an extension within this (say as a PR), or with my own code alongside this (say as app logic).

What is the recommendation from this library author regarding adding support for more providers? Should they be done via PRs, copy paste implementations?

**Comment by JudahGabriel** [comment]
Awesome. I'll see what I can do. I was looking at Sign In with Apple the other day, looks very easy to implement.

You can make a PR. Have a look at the [Google provider](https://github.com/pwa-builder/pwa-auth/blob/master/src/google-provider.ts) as an example. In short: you should have a signIn method that returns a `Promise<SignInResult>`.

Alternately, if you're more comfortable just sending over some sample code to get someone started on the provider, that'd be the next best thing.

**Comment by balupton** [comment]
@JudahGabriel great! thank you

I'll see what @bevry can do regarding a goodreads option. That said, goodreads auth does not provide any user information, only an api key to query their service on behalf of the user. It seems this library expects user information to be returned, and seems that linking accounts into one account is not intended.

My goal workflow would be:

1. User signs in, restricted to auth providers that provide emails
2. User once signed in, has option of connecting others accounts, making any provided email address an alias, and storing their provided data, such as the goodreads user api key in the case of goodreads
3. Now the user has one account with multiple emails and if they linked their goodreads, their goodreads api key

**Comment by JudahGabriel** [comment]
Looking at goodreads just briefly, it seems they allow users to login with Facebook, Amazon, or their own (email/password) accounts. 

pwa-auth is generally geared towards login providers that provide a valid email address (and optionally, a name and profile picture). I'm not opposed to possible integrations outside that framework if there is a good use case.

**Comment by JudahGabriel** [comment]
FWIW, here's the [documentation for Sign In with Apple](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple). Looks pretty straighforward.

**Comment by JudahGabriel** [comment]
Played around with it tonight, following the [instructions here](https://help.apple.com/developer-account/?lang=en#/dev1c0e25352). Couldn't get it to work - Apple OAuth keeps saying "Invalid Redirect URI", even though I've added the redirect URIs to my App + Service + Key on the Apple Dev portal, per their instructions.

Maybe I'll give it another shot later.

**Comment by balupton** [comment]
What redirect URI are you using? Perhaps there are requirements for it.

**Comment by JudahGabriel** [comment]
Have a [look at it here](https://pwa-auth-ios.glitch.me), [code here](https://glitch.com/~pwa-auth-ios).

That *should* work, because I've followed the Apple documentation about how to add your redirect URIs. Here's what it looks like on the Apple dev portal:

![image](https://user-images.githubusercontent.com/312936/80026325-d020e900-8496-11ea-9553-f569de18ee33.png)

As you can see, I've listed the URL there correctly. Not sure what's wrong. I see [this Stackoverflow question](https://stackoverflow.com/q/61071848/536) is basically the same problem I'm hitting.

**Comment by JudahGabriel** [comment]
OK, I found the issue. The "domains and subdomains" section doesn't allow HTTPS, but return URLs does. I had to specify "https" for the Return URLs. Meanwhile, you *cannot* specify "https" for the domains and subdomains, or you'll get a generic "invalid domain" error. 

Yikes. 

Talk about bad UI design and poor error handling.

Anyways, now it looks like I'll be able to sign-in, which means pwa-auth will support "Sign in with Apple" soon. 😎

**Comment by JudahGabriel** [comment]
Next issue is that Apple only sends the user information the very first time. Successive sign-ins won't return user information, only a code and id_token. 

Gah, once again I am reminded how terrible Apple's dev platform is.

For this to work in pwa-auth, we'd need to match up the code and ID token to the user. I think that has to happen on a backend server, unfortunately. Investigating...

**Comment by JudahGabriel** [comment]
I got it working! **pwa-auth now supports Sign in with Apple**. Here's a screenshot of it running locally:

In the default button appearance:
![image](https://user-images.githubusercontent.com/312936/80068217-13f60b80-84f4-11ea-82bc-ce85833f2991.png)

With list appearance:
![image](https://user-images.githubusercontent.com/312936/80068325-46076d80-84f4-11ea-8821-ed1b41b17dfe.png)

Apple OAuth prompt:
![image](https://user-images.githubusercontent.com/312936/80068657-d8a80c80-84f4-11ea-878d-a17db7477b59.png)

Some caveats:
- Profile pic: Apple doesn't support fetching user's profile image. AFAICT, Apple just doesn't support that.
- User name on first login only: Apple returns the user's name the very first time he logs into your app. It's on app devs to store that on first login. Successive logins won't return the user name. pwa-auth tries to alleviate that -- through stored credentials, and even local storage -- but it's still possible you won't get a user name. Devs need to store the user name on first sign-in.
- Real/proxied email address: Apple can optionally hide the user's real email from you. When the user signs in with Apple, the user is prompted "do you want to share your email address with XYZ App?" If they choose yes, you get their real email. If they choose no, you get a Apple-proxied email address which you can still contact the user through, but the user can turn off at anytime. 🤷‍♀️
- To create your own Apple key, you have to be a member of the Apple Developer Program, and that costs $99/year. 😭 (Caveat; 501c3 non-profits can join for free.)

I've published this new support as pwa-auth 0.9.6. I'll update the docs with the new provider information this week.

**Comment by balupton** [comment]
Fantastic. Good work

**Comment by rajandimri** [comment]
This is amazing 👍
