### ISSUE TITLE
Setting appearance property to list does not apply the proper style

### ISSUE THREAD

**Issue by nmetulev** [pwa-builder/pwa-auth#9]
Per https://github.com/nmetulev/wc-react/issues/1

[The pwa-auth component styles the component based on the attribute value](https://github.com/pwa-builder/pwa-auth/blob/master/src/pwa-auth.ts#L40). However, when the 'appearance' value is set as a property in js, it is not reflected to the attribute so the style does not get applied. 

The fix here should be to ensure the `appearance` property is [reflected to the attribute](https://lit-element.polymer-project.org/guide/properties#reflected-attributes) or the component is not styled by an attribute value.

**Comment by JudahGabriel** [comment]
Thanks! I'll have a look.

**Comment by JudahGabriel** [comment]
I've pushed a fix for this. We'll have a new release out by end of today.

**Comment by JudahGabriel** [comment]
Pushed a new release, pwa-auth 0.9.5, with the fix.

**Comment by Odonno** [comment]
Sweet. I will try it asap.

**Comment by Odonno** [comment]
Thank you guys, it works perfectly!
